# Generated by Django 5.2.4 on 2025-07-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('credits', models.PositiveIntegerField(default=3)),
                ('category', models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('OPTIONAL', 'Optional'), ('SPECIALIZED', 'Specialized')], default='CORE', max_length=20)),
                ('semester', models.CharField(choices=[('fall_2024', 'Fall 2024'), ('spring_2025', 'Spring 2025'), ('summer_2025', 'Summer 2025'), ('fall_2025', 'Fall 2025')], default='fall_2024', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, to='modules.module')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'modules',
                'ordering': ['code'],
            },
        ),
    ]
