# Generated by Django 4.2.23 on 2025-08-19 12:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_code', models.SlugField(help_text='Course code (e.g., CS-PROG)', max_length=20, unique=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_available_for_registration', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(help_text='Module code (e.g., CS101)', max_length=20)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='URL for module image', null=True)),
                ('credits', models.PositiveIntegerField(help_text='Number of credits for this module', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('category', models.CharField(choices=[('core', 'Core Module'), ('elective', 'Elective Module'), ('optional', 'Optional Module'), ('foundation', 'Foundation Module')], default='core', max_length=20)),
                ('prerequisites', models.TextField(blank=True, help_text='Prerequisites for this module')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_available_for_registration', models.BooleanField(default=True)),
                ('max_students', models.PositiveIntegerField(blank=True, help_text='Maximum number of students allowed (leave blank for unlimited)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='modules.course')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['code'],
                'unique_together': {('course', 'code')},
            },
        ),
    ]
