# Generated by Django 5.2.4 on 2025-07-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL for module image', null=True),
        ),
    ]
