# Generated by Django 5.2.4 on 2025-07-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL for module image (e.g., from Unsplash)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'),
        ),
    ]
