# Generated by Django 5.2.4 on 2025-08-19 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('optional', 'Optional'), ('prerequisite', 'Prerequisite')], default='core', max_length=20)),
                ('description', models.TextField()),
                ('availability', models.BooleanField(default=True)),
                ('max_students', models.PositiveIntegerField(default=100, help_text='Maximum number of students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='module',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='module',
            name='category',
        ),
        migrations.RemoveField(
            model_name='module',
            name='max_students',
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='modules.course'),
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='modules.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='students.student')),
            ],
            options={
                'ordering': ['-date_registered'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
