# Generated by Django 5.2.4 on 2025-08-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_add_course_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_students',
        ),
        migrations.AddField(
            model_name='module',
            name='availability',
            field=models.BooleanField(default=True, help_text='Is this module available for registration?'),
        ),
        migrations.AddField(
            model_name='module',
            name='max_students',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of students'),
        ),
        migrations.DeleteModel(
            name='CourseRegistration',
        ),
    ]
