# Generated by Django 5.2.4 on 2025-07-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_module_image_url_alter_module_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='max_students',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of students that can register for this module'),
        ),
    ]
