# Generated by Django 5.2.4 on 2025-07-31 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_module_max_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='semester',
        ),
    ]
