# Generated by Django 5.2.4 on 2025-08-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_module_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
    ]
