# Generated by Django 5.2.4 on 2025-07-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.CharField(blank=True, help_text='Final grade (A, B, C, D, F)', max_length=5, null=True),
        ),
    ]
