# Generated by Django 5.2.4 on 2025-07-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
