# Generated by Django 5.2.4 on 2025-07-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdate',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
