# Generated by Django 5.2.4 on 2025-07-29 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0002_contactmessage_is_resolved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemstats',
            options={'ordering': ['-date_recorded'], 'verbose_name': 'System Statistics', 'verbose_name_plural': 'System Statistics'},
        ),
        migrations.AddField(
            model_name='systemstats',
            name='active_registrations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemstats',
            name='completed_registrations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemstats',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
