# Generated by Django 5.2.4 on 2025-07-28 20:00

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    NewsUpdate = apps.get_model('sitecore', 'NewsUpdate')
    for news in NewsUpdate.objects.all():
        if not news.slug:
            base_slug = slugify(news.title)
            slug = base_slug
            counter = 1
            while NewsUpdate.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            news.slug = slug
            news.save()


def reverse_populate_slugs(apps, schema_editor):
    NewsUpdate = apps.get_model('sitecore', 'NewsUpdate')
    NewsUpdate.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0002_newsupdate_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
