# Generated by Django 5.2.4 on 2025-07-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalcontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='is_registration_open',
            field=models.BooleanField(default=True, help_text='Is module registration currently open?'),
        ),
    ]
